
services:
  scala-sbt:
    container_name: scala-sbt
    build:
      context: ./ # Dockerfile para o Scala
      dockerfile: Dockerfile
    environment:
      - STORAGE_PATH=wasbs://dev@azurite:10000/dev/output.parquet
    volumes:
      - ./projetoNome:/app # Código-fonte do host para o container
      - ./host-shared-jar:/app/target # Volume para o JAR gerado
    healthcheck:
      test: ["CMD", "ls", "/app/target"]
      interval: 10s
      timeout: 5s
      retries: 3
      
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000" # Blob service
      - "10001:10001" # Queue service
      - "10002:10002" # Table service
    volumes:
      - azurite_data:/data
    environment:
      - AZURITE_ACCOUNTS=dev:MTIzNDU2Nzg5YWJjZGVm
    depends_on:
      scala-sbt:
        condition: service_healthy
  spark-master:
    image: bitnami/spark:3.5
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8080:8080"
    depends_on:
     - azurite    

  spark-worker:
    image: bitnami/spark:3.5
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2 # Número de núcleos de CPU
      - SPARK_WORKER_MEMORY=2G # Memória alocada para o worker       
      - STORAGE_PATH=wasbs://dev@azurite:10000/dev/output.parquet
      - INPUT_PATH=/files/fake.txt
    ports:
    - "8081:8081"
    depends_on:
      spark-master:
        condition: service_started
      scala-sbt:
        condition: service_healthy
    volumes:
      - ./host-shared-jar:/app/target # Volume para acessar o JAR gerado
    command: >
      /opt/bitnami/spark/bin/spark-submit
      --class Main
      --master spark://spark-master:7077
      --deploy-mode client
      /app/target/scala-2.13/projetonome_2.13-0.1.0-SNAPSHOT.jar MinhaAplicacaoSpark

volumes:
  azurite_data: